### ISSUE TITLE
bug in file name

### ISSUE THREAD

**Issue by ewalker1974** [sriramveeraghanta/vue-autoresize-textarea#1]
When build assets the following error occurs
This relative module was not found:

* ./components/App.vue in ./node_modules/vue-autoresize-textarea/src/index.js
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The reason of error the name of component app.vue: /src/components/app.vue
and import in index.js
 import autoresize from './components/App.vue'

**Comment by vokamut** [comment]
@sriramveeraghanta, please, fix this bug

**Comment by sriramveeraghanta** [comment]
Fixed the file name issue and generating the bundle using bili. Please use the updated version
[https://github.com/sriramveeraghanta/vue-autoresize-textarea/releases/tag/0.2](url)
